# Generated by Django 5.1.2 on 2024-10-21 15:47

import Resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0002_video_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to=Resources.models.upload_to, validators=[Resources.models.ValidateImageFileExtension()])),
            ],
        ),
    ]
