# Generated by Django 5.1.2 on 2024-10-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resources', '0003_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form2Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Form 2 Video',
                'verbose_name_plural': 'Form 2 Videos',
            },
        ),
        migrations.CreateModel(
            name='Form3Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Form 3 Video',
                'verbose_name_plural': 'Form 3 Videos',
            },
        ),
        migrations.CreateModel(
            name='Form4Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Form 4 Video',
                'verbose_name_plural': 'Form 4 Videos',
            },
        ),
        migrations.RenameModel(
            old_name='Video',
            new_name='Form1Video',
        ),
        migrations.AlterModelOptions(
            name='form1video',
            options={'verbose_name': 'Form 1 Video', 'verbose_name_plural': 'Form 1 Videos'},
        ),
    ]
